### ISSUE TITLE
feature request: uniform struct members

### ISSUE THREAD

**Issue by mfiano** [3b/3bgl-shader#7]
Currently I am doing something like this to obtain all of the uniforms for a shader program:

```lisp
(defun shader-program-uniforms (&rest stages)
  (apply #'union
         (loop :for (stage . func) :in (alexandria:plist-alist stages)
               :collect 
               (loop :for (lisp nil nil) :in (nth-value 1 (3bgl-shaders:generate-stage stage func))
                     :collect (alexandria:make-keyword lisp)))))
```

For my example shader this looks like:
```lisp
(shader-program-uniforms :vertex 'vertex-default :fragment 'fragment-default)
;; => (:SCALE :PROJ :VIEW :MODEL :TEX)
```

However, `:TEX` is actually a struct, and I need to pass each member to the shader. I'm using glkit, and I need to know there is `:tex.image`, `:tex.size-layer`, etc needed for uniforms. Is it at all possible to extend the 2nd return value of `generate-stage` to include more information if the uniforms are structs? This would probably be the single most helpful feature that could be added for my uses, and would simplify a lot of my code.

**Comment by 3b** [comment]
Started working on that on [expand-uniforms](https://github.com/3b/3bgl-shader/tree/expand-uniforms) branch. Pass `:expand-uniforms t` to `generate-stage`, and the returned uniforms should end with a plist containing `:components (...)` with a list of expanded uniform parts in the form of a list of lisp names.

Let me know if it works (minimally tested, so probably missed a bunch of edge cases), and if that is a useful API or if you have better ideas for it...

**Comment by 3b** [comment]
so your example would turn into something like 
```lisp
(defun shader-program-uniforms (&rest stages)
  (loop :for (stage func) :on stages :by #'cddr
        :append
        (loop :for (lisp nil nil . props) :in (nth-value 1 (3bgl-shaders:generate-stage stage func :expand-uniforms t))
              :for components = (getf props :components)
              :append (if components
                          (mapcar 'alexandria:make-keyword
                                  (mapcar 'princ-to-string components))
                          (alexandria:make-keyword lisp)))))
```

**Comment by mfiano** [comment]
This works great. Closing issue.
